def offen():
  setup(1)
  intake.spin_for(FORWARD,1,TURNS,wait=False)
  move(49)
  turn(90)
  intake.spin_for(REVERSE,1,TURNS,wait=False)
  move(9)
  move(-19)
  turn(-90)
  intake.spin_for(FORWARD,2,TURNS,wait=False)
  move(5)
  move(-7)
  turn(90)
  intake.spin_for(REVERSE,3,TURNS,wait=False)
  move(20)
  move(-6)
  turn(80)
  move(47)
  turn(97)
  move(27.4)
def defen():
  pass